/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ShellImport } from './routes/_shell'
import { Route as ShellIndexImport } from './routes/_shell.index'

// Create/Update Routes

const ShellRoute = ShellImport.update({
  id: '/_shell',
  getParentRoute: () => rootRoute,
} as any)

const ShellIndexRoute = ShellIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ShellImport
      parentRoute: typeof rootRoute
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexImport
      parentRoute: typeof ShellImport
    }
  }
}

// Create and export the route tree

interface ShellRouteChildren {
  ShellIndexRoute: typeof ShellIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellIndexRoute: ShellIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof ShellRouteWithChildren
  '/': typeof ShellIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof ShellIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_shell': typeof ShellRouteWithChildren
  '/_shell/': typeof ShellIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/'
  id: '__root__' | '/_shell' | '/_shell/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_shell"
      ]
    },
    "/_shell": {
      "filePath": "_shell.tsx",
      "children": [
        "/_shell/"
      ]
    },
    "/_shell/": {
      "filePath": "_shell.index.tsx",
      "parent": "/_shell"
    }
  }
}
ROUTE_MANIFEST_END */
