/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ShellImport } from './routes/_shell'
import { Route as ShellIndexImport } from './routes/_shell.index'
import { Route as ShellRecipesIndexImport } from './routes/_shell.recipes.index'
import { Route as ShellRecipesRecipeIdImport } from './routes/_shell.recipes.$recipeId'

// Create/Update Routes

const ShellRoute = ShellImport.update({
  id: '/_shell',
  getParentRoute: () => rootRoute,
} as any)

const ShellIndexRoute = ShellIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)

const ShellRecipesIndexRoute = ShellRecipesIndexImport.update({
  id: '/recipes/',
  path: '/recipes/',
  getParentRoute: () => ShellRoute,
} as any)

const ShellRecipesRecipeIdRoute = ShellRecipesRecipeIdImport.update({
  id: '/recipes/$recipeId',
  path: '/recipes/$recipeId',
  getParentRoute: () => ShellRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ShellImport
      parentRoute: typeof rootRoute
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexImport
      parentRoute: typeof ShellImport
    }
    '/_shell/recipes/$recipeId': {
      id: '/_shell/recipes/$recipeId'
      path: '/recipes/$recipeId'
      fullPath: '/recipes/$recipeId'
      preLoaderRoute: typeof ShellRecipesRecipeIdImport
      parentRoute: typeof ShellImport
    }
    '/_shell/recipes/': {
      id: '/_shell/recipes/'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof ShellRecipesIndexImport
      parentRoute: typeof ShellImport
    }
  }
}

// Create and export the route tree

interface ShellRouteChildren {
  ShellIndexRoute: typeof ShellIndexRoute
  ShellRecipesRecipeIdRoute: typeof ShellRecipesRecipeIdRoute
  ShellRecipesIndexRoute: typeof ShellRecipesIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellIndexRoute: ShellIndexRoute,
  ShellRecipesRecipeIdRoute: ShellRecipesRecipeIdRoute,
  ShellRecipesIndexRoute: ShellRecipesIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof ShellRouteWithChildren
  '/': typeof ShellIndexRoute
  '/recipes/$recipeId': typeof ShellRecipesRecipeIdRoute
  '/recipes': typeof ShellRecipesIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof ShellIndexRoute
  '/recipes/$recipeId': typeof ShellRecipesRecipeIdRoute
  '/recipes': typeof ShellRecipesIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_shell': typeof ShellRouteWithChildren
  '/_shell/': typeof ShellIndexRoute
  '/_shell/recipes/$recipeId': typeof ShellRecipesRecipeIdRoute
  '/_shell/recipes/': typeof ShellRecipesIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '' | '/' | '/recipes/$recipeId' | '/recipes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/recipes/$recipeId' | '/recipes'
  id:
    | '__root__'
    | '/_shell'
    | '/_shell/'
    | '/_shell/recipes/$recipeId'
    | '/_shell/recipes/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_shell"
      ]
    },
    "/_shell": {
      "filePath": "_shell.tsx",
      "children": [
        "/_shell/",
        "/_shell/recipes/$recipeId",
        "/_shell/recipes/"
      ]
    },
    "/_shell/": {
      "filePath": "_shell.index.tsx",
      "parent": "/_shell"
    },
    "/_shell/recipes/$recipeId": {
      "filePath": "_shell.recipes.$recipeId.tsx",
      "parent": "/_shell"
    },
    "/_shell/recipes/": {
      "filePath": "_shell.recipes.index.tsx",
      "parent": "/_shell"
    }
  }
}
ROUTE_MANIFEST_END */
